### ISSUE TITLE
Fix -w

### ISSUE THREAD

**Issue by petdance** [petdance/ack3#10]
Redo the `-w` flag to properly handle words.

Update documentation that this affects.

**Comment by n1vux** [comment]
xref discussion under https://github.com/petdance/ack2/issues/445 Metacharacters and Non-Word chars ; https://github.com/petdance/ack2/issues/565 Unicode (ugh but should have tests to track what DOES work or new enough perls)

**Comment by petdance** [comment]
This needs #1 for proper testing.

**Comment by petdance** [comment]
Right now this has been changed to this:

```
    if ( $opt->{w} ) {
        $str = "\\b(?:$str)\\b";
    }  
```

Not sure if this is what we want to live with.

**Comment by n1vux** [comment]
As discussed on prior thread, that handles the commonsense case (where `$str` is in fact a sensible literal word, or a RE that will match word-chars only) but has nasty edge/corner cases when `$str` may match whitespace or non-word-punc in first or last position.

root issue is that the `\b` zerowidth assertion treats non-word printables asymmetrically from word-printable, in that (1)there is no `\b` within sequente space punc space punc, and (2)the beginning and end of string are Non-word for `\b` purposes so `\b(-foo-)\b` will not match in first or last position ever. 

we must either document that only the commonsense case where -w means word means word and Warn/Error if pattern $str starts or ends with non-word punc [including  metachas; if you want `-w $RE` you should drop the -w and say which word-effect you want]  *or* define exactly what -w means for $str to match a non-word word in documentation and tests and then implement it.  

We discussed some ways using \k etc to make it work in edge cases but depends what we want the edges to be.

**Comment by petdance** [comment]
I'll be getting at those edge cases today.  That's why I didn't close this.

**Comment by petdance** [comment]
`(?:^|\b|\s)\K(?:PATTERN)(?=\s|\b|$)` is what we talked about latest.

**Comment by petdance** [comment]
We may also want to make an optimization such that if `$pattern =~ /^\w+$/` that we use the simple `\b$pattern\b`.

**Comment by patch** [comment]
`\b{wb}` would be better than `\b`, at least for acking natural language, but it is relatively new to Perl and the semantics are less well-known than programmers’ longstanding expectations of “word boundaries.”

**Comment by petdance** [comment]
When did it come around?  I'm not familiar with it.

**Comment by patch** [comment]
Perl 5.22 with notable improvements in 5.24.

References:
* [perl5220delta: `qr/\b{wb}/`](https://metacpan.org/pod/distribution/perl/pod/perl5220delta.pod#qr/%5Cb%7Bwb%7D/)
* [perl5240delta: `qr/\b{wb}/` is now tailored to Perl expectations](https://metacpan.org/pod/distribution/perl/pod/perl5240delta.pod#qr/%5Cb%7Bwb%7D/-is-now-tailored-to-Perl-expectations)
* [perlrebackslash: `\b{wb}`](https://metacpan.org/pod/distribution/perl/pod/perlrebackslash.pod#\b{wb})

**Comment by petdance** [comment]
Interesting.  Thanks for the pointers.

I would never put something in ack where the behavior changes depending on what version of Perl is running.

**Comment by patch** [comment]
The regex syntax and semantics change in every Perl release, including those of `\b` when new Unicode “word” characters are added, and therefore those of ack change as well, but I understand your desire for a relatively stable flag.
