### ISSUE TITLE
Add feature to group consecutive lines: the clumping feature

### ISSUE THREAD

**Issue by petdance** [petdance/ack3#16]
—clump would have to be mutex with any of the context flags.   Non-consecutive lines get a blank line between them.

```
$ ack foo

100: foo
101: foo
102: foo

110: foo

168: foo

189: foo
190: foo

202: foo
```

**Comment by petdance** [comment]
Maybe it's `-a, --adjacent`.

**Comment by n1vux** [comment]
> Maybe it's -a, --adjacent.


GNU grep uses -a as a synonym for --text
    "Process a binary file as if it were text; this is equivalent to
the --binary-files=text option"

which I guess is irrelevant since we won't do that ?

https://www.gnu.org/software/grep/manual/grep.html  ( sect.  2.1.6 )

**Comment by petdance** [comment]
That's kinda funny since `-a` in ack 1 had a similar effect.

Mostly I'm trying to come up with a good word that evokes the effect that it will have.

**Comment by petdance** [comment]
Mutex flags for `--clump`: `-f`, `-g`, `-l` (anything that lists files), `-A`, `-B`, `-C` (it conflicts with context), `-c` (counting)

It *can* deal with `--group` and `--nogroup`, and should be explicitly tested with them.

**Comment by petdance** [comment]
`--clump` needs to force a line break between files.

**Comment by petdance** [comment]
It's now `--proximate`.
