### ISSUE TITLE
--output to provide alternate for $filename

### ISSUE THREAD

**Issue by n1vux** [petdance/ack3#93]
Subsequent to #91 and patch `Allow \r, \n and \t in --output` [petdance/ack3@f61aa58](https://github.com/petdance/ack3/commit/f61aa5821a15cb0601ad968e3512f31119be772b), to fully support Fowler's useful example and emulating grep we need a substitute for `$filename` too

**Error message format emulation for IDE magic**
> However the smartest thing I've ever used the custom output for is to generate lines that look just like Perl error messages:
> ```   
> ack --no-filename --no-group \
>        --output 'at $filename line $line_no$/$line$/' \
>        'sub new'
> ```
> Why is this so helpful? Because I use the PerlErrorSublime.popclipext PopClip extension to allow me to highlight any perl-error like string in my terminal and open that line in Sublime Text:
> http://www.perladvent.org/2014/2014-12-21.html
(He used `$/` as an alias to work around `'\n'` in ack2, but not needed now that we have **\n** special case.)

**Grep emulation**  (a specific case of above)
`ack --output='$filename:$.:$line'  ` may  seem useless since it's the default output (modulo highlight which can be controlled) but if i want that format but use something else useful `--output='$filename:$.:$+'` etc, or if i want that format but with a shell loop instead of long CLI `@ARGV`
either shell `for` or  `find... -print0 | xargs -0 -n 1 ack --output='$filename:$.:$_'  $pattern `  emulating multifile format. (or `ack -g` of course !)

**Suggestions**
Reasonable alternatives are `$F`  `$f` or `$*` .  
Former special var `$*` is deprecated  so is available for this use and is mnemonic for ARGV, but might be confusing, and might be reused by P5P someday. 
`$F[$1]` has special meaning which might confuse folks when using scalar `$F` .
So `$f` might be safer, and is obviously not a Perl Built-in.

Possible implementation  ... add 'f' to `@supported_special_variables = ... qw...` 
and then 
`$keep{f} = $filename if $special_vars_used_by_opt_output =~ /f/ ;` after initial keep
( `if exists $keep{f}` (not necessarily defined, likely `undef` likely *faster* ?) 

Original discussion on [#ack](https://beyondgrep.slack.com/archives/C4J886HT2/p1501211021968413)

**Comment by petdance** [comment]
Done https://github.com/petdance/ack3/commit/5dfb28d459769e6944c439d32069763994e9395a
